services:
    - type: web
    name: aksiya-halol-bot
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
            - key: TELEGRAM_TOKEN
        sync: false
            - key: CHAT_ID
        value: "745170275"